# Generated by Django 5.0.1 on 2024-01-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dailyprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_background', models.CharField(blank=True, max_length=255, null=True)),
                ('per_day_salary', models.CharField(blank=True, max_length=255, null=True)),
                ('year_of_experience', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='mentor',
            new_name='project_manager',
        ),
    ]
